### ISSUE TITLE
Make ascii2mathml dependency optional.

### ISSUE THREAD

**Issue by leipert** [runarberg/markdown-it-math#13]
Hey, once me again.

We have the problem that a dependency in `ascii2mathml` breaks our installation (namely `fsevents` in `chokidar` in the `babel` package). See here: https://github.com/Galadirith/markdown-preview-plus/issues/118

Do you think it would be possible to provide markdown-it-math with an optional dependency ascii2mathml or even without ascii2mathml? If yes, I could also help you expanding docs that explain how to use this package together with Mathjax or KaTeX.

Thanks!

**Comment by runarberg** [comment]
Sure, [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies) seems to be a perfect fit for a default behavior from a third party tool. I simply didn't know about it.

It has happened to me that I was unable to build `ascii2mathml` due to an error in the same package, I attributed that to a faulty nvm installation of a specific version, installing it with the system version of node has [always worked](https://travis-ci.org/runarberg/ascii2mathml).

I would appreciate help with documenting how to use this package with MathJax or KaTeX, although it saddens me that in 2015 we are still dependent on these tools. If only blink would implement MathML (or if atom was build on gecko) you guys could rather be using [TeXZilla](https://github.com/fred-wang/TeXZilla) and you would get both smaller bundle and faster rendering. It is silly that a document compiled into a format that is easy for the computer to parse needs a scripting layer on top of that just to be able to render math.

**Comment by leipert** [comment]
Yeah. I also found [codependency](https://www.npmjs.com/package/codependency) as another viable solution.

Regarding the docs. I will write something up after the 9th of October as I am currently working on my Bachelor Thesis.

Well. It is how it is, we have MathJax Support now and it looks nice (although I like KaTeX more). In our next release it will include [an electron build](https://github.com/Galadirith/MathJax/tree/release-2.4.0-electron) which is _only a few_ megabytes.

And well, it would be cool, if we could use mathm in atom, but this is how it is. I mean we should be happy that we get live rendering at all :dancer:

**Comment by runarberg** [comment]
[Here](https://travis-ci.org/runarberg/markdown-it-math/jobs/81028510#L91) is the problem I suppose.
