### ISSUE TITLE
Math Blocks should behave like code fences

### ISSUE THREAD

**Issue by leipert** [runarberg/markdown-it-math#7]
``````
Code fences can start right after a paragraph
```javascript
var x = y;
```
In my opinion math blocks should also work that way:
$$
x + y
$$
wuhu 
``````

**Comment by runarberg** [comment]
Thank you

**Comment by geyang** [comment]
this is simply incorrect. The math blocks should not behave like code fences because
1. LaTeX does not enforce this, and a lot of users do not use `$$` this way.
2. math blocks are inline-block elements instead of block elements. This should be respected by the markdown syntax as well. 

I agree that it is visually appealing to have the display math blocks syntax like this, but again it is not standard and the current html generated is incorrect.

see #17
